### PR TITLE
Fix clone3 syscall

### PR DESCRIPTION
**Pull request by lucaskanashiro**
For more info: https://bugs.launchpad.net/cloud-images/+bug/1943049

autopkgtest is still happy:

```
autopkgtest [11:35:16]: @@@@@@@@@@@@@@@@@@@@ summary
basic-smoke          PASS
docker-in-lxd        PASS
```

### CODE REVIEW

**Comment by mwhudson** [comment]
This LGTM. How much work do you think it would be to implement a dep8 test that deboostrapped the devel series and did some minimal tests of that? Or something in that vein? I guess dep8 testing the devel series in an LTS backport is a bit odd as it can be broken by changes outside of what the test runner thinks is being tested but otoh it would be really good to know about this sort of thing sooner...

(This doesn't have to be done before we merge this, it would just be a good thing to have)

**Comment by lucaskanashiro** [comment]
I updated my branch with the latest changes @tianon made to his upstream PR. Could @mwhudson or @tianon give me a +1 on this?

**Comment by lucaskanashiro** [comment]
> This LGTM. How much work do you think it would be to implement a dep8 test that deboostrapped the devel series and did some minimal tests of that? Or something in that vein? I guess dep8 testing the devel series in an LTS backport is a bit odd as it can be broken by changes outside of what the test runner thinks is being tested but otoh it would be really good to know about this sort of thing sooner...

I believe we should definitely have a dep8 test like that. In order to avoid the problem you mentioned when backporting it to LTS releases, we could check in the test if it's running in a development release, if not we return the `77` exit code and mark the test as skippable, with this it would be skipped in non-development releases.

> (This doesn't have to be done before we merge this, it would just be a good thing to have)

Agreed. We can release this change now, and then work on this dep8 test in a separate branch.

**Review by tianon — APPROVED** [review]
:+1:

**Pull request merged**
